services:
  postgres:
    image: postgres:16-alpine
    container_name: mm-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mm_db
    volumes:
      - mm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otc_user -d otc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mm-network

  rift-market-maker:
    container_name: market-maker
    build:
      context: .
      dockerfile_inline: |
        FROM rust:1.88 AS builder
        WORKDIR /app
        COPY . .
        RUN cargo build --release --bin market-maker 

        FROM debian:bookworm-slim
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/market-maker /app/
        CMD ["./market-maker"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      RUST_LOG: info
      MM_TAG: ${MM_TAG}
      MM_ID: ${MM_ID}
      MM_API_SECRET: ${MM_API_SECRET}
      OTC_WS_URL: ${OTC_WS_URL}
      RFQ_WS_URL: ${RFQ_WS_URL}
      BITCOIN_WALLET_DB_PATH: /app/bitcoin-wallet-db/wallet.sqlite
      BITCOIN_WALLET_DESCRIPTOR: ${BITCOIN_WALLET_DESCRIPTOR}
      BITCOIN_WALLET_NETWORK: bitcoin
      BITCOIN_WALLET_ESPLORA_URL: ${BITCOIN_WALLET_ESPLORA_URL}
      ETHEREUM_WALLET_PRIVATE_KEY: ${ETHEREUM_WALLET_PRIVATE_KEY}
      ETHEREUM_RPC_WS_URL: ${ETHEREUM_RPC_WS_URL}
      TRADE_SPREAD_BPS: ${TRADE_SPREAD_BPS}
      FEE_SAFETY_MULTIPLIER: ${FEE_SAFETY_MULTIPLIER}
      BALANCE_UTILIZATION_THRESHOLD_BPS: ${BALANCE_UTILIZATION_THRESHOLD_BPS}
      MM_DATABASE_URL: postgres://user:pass@postgres:5432/mm_db
      COINBASE_EXCHANGE_API_KEY: ${COINBASE_EXCHANGE_API_KEY}
      COINBASE_EXCHANGE_API_PASSPHRASE: ${COINBASE_EXCHANGE_API_PASSPHRASE}
      COINBASE_EXCHANGE_API_SECRET: ${COINBASE_EXCHANGE_API_SECRET}
      COINBASE_EXCHANGE_API_BASE_URL: https://api.exchange.coinbase.com
      INVENTORY_TARGET_RATIO_BPS: ${INVENTORY_TARGET_RATIO_BPS}
      REBALANCE_TOLERANCE_BPS: ${REBALANCE_TOLERANCE_BPS}
      AUTO_MANAGE_INVENTORY: ${AUTO_MANAGE_INVENTORY}

    networks:
      - mm-network
    volumes:
      - market_maker_bitcoin_wallet_db_data:/app/bitcoin-wallet-db
    platform: linux/amd64

networks:
  mm-network:
    driver: bridge

volumes:
  mm_postgres_data:
  market_maker_bitcoin_wallet_db_data:
