services:
  db:
    image: postgres:15-alpine
    container_name: test_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ${POSTGRES_DB:-otc_dev}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d otc_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
