configs:
  bitcoin-entrypoint:
    content: |
      #!/bin/bash
      set -euo pipefail
      archive_url="https://rift-blockchain-archive.s3.us-west-1.amazonaws.com/bitcoind-datadir-2025-09-11.tar.lz4"

      echo "Checking Bitcoin directory: $$BITCOIN_DATA_DIR"

      if [[ ! -d "$$BITCOIN_DATA_DIR/blocks" ]] && [[ ! -d "$$BITCOIN_DATA_DIR/chainstate" ]]; then
          echo "Bitcoin data directory appears to be empty. Downloading blockchain data..."
          echo "This may take a while depending on your internet connection..."
          
          temp_dir="$$(mktemp -d)"
          trap "rm -rf $$temp_dir" EXIT
          
          echo "Downloading from: $$archive_url"
          
          archive_file="$$temp_dir/blockchain-archive.tar.lz4"
          echo "Downloading to temporary file: $$archive_file"
          echo "Using aria2c with 8 parallel connections for optimal speed..."
          
          if aria2c \
              --max-connection-per-server=8 \
              --split=8 \
              --max-concurrent-downloads=1 \
              --continue=true \
              --retry-wait=5 \
              --max-tries=3 \
              --timeout=60 \
              --connect-timeout=10 \
              --file-allocation=none \
              --check-integrity=false \
              --summary-interval=10 \
              --download-result=hide \
              --console-log-level=info \
              --dir="$$temp_dir" \
              --out="blockchain-archive.tar.lz4" \
              "$$archive_url"; then
              
              echo "Download completed. Extracting archive directly to $$BITCOIN_DATA_DIR..."
              if tar -I lz4 -xf $$archive_file -C $$BITCOIN_DATA_DIR; then
                  rm -f $$archive_file
                  echo "Download and extraction successful"
                  
                  
                  chown -R bitcoin:bitcoin $$BITCOIN_DATA_DIR
                  
                  echo "Blockchain data initialization complete"
                  echo "Data directory size: $(du -sh $$BITCOIN_DATA_DIR | cut -f1)"
              else
                  echo "Error: Failed to extract archive"
                  rm -f $$archive_file
                  echo "Warning: Failed to download blockchain data. Bitcoin will sync from genesis block."
                  echo "This will take significantly longer but is still functional."
              fi
          else
              echo "Warning: Failed to download blockchain data. Bitcoin will sync from genesis block."
              echo "This will take significantly longer but is still functional."
          fi
      else
          echo "Bitcoin data directory already contains blockchain data"
          echo "Data directory size: $(du -sh $$BITCOIN_DATA_DIR | cut -f1)"
      fi
      rm -rf /tmp/*

      echo "Starting Bitcoin Core with arguments: $*"
      exec bitcoind "$@"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tee-otc-postgres
    environment:
      POSTGRES_USER: otc_user
      POSTGRES_PASSWORD: otc_password
      POSTGRES_DB: otc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otc_user -d otc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tee-network

  helios:
    container_name: tee-helios
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:24.04
        RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*
        RUN curl -L 'https://github.com/a16z/helios/releases/download/0.9.0/helios_linux_amd64.tar.gz' | tar -xzC /usr/local/bin
        EXPOSE 8545
        WORKDIR /root
        CMD [ "helios", "ethereum", "--execution-rpc", "${UNTRUSTED_EVM_RPC_URL}", "--checkpoint", "0xf95f9c34be687e3cef0906d25e51f3568798fb11155b00d715416dba3d70a313", "--rpc-bind-ip", "0.0.0.0"]
    environment:
      UNTRUSTED_EVM_RPC_URL: ${UNTRUSTED_EVM_RPC_URL}
    ports:
      - "8550:8545"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s -X POST http://localhost:8545 -H "Content-Type: application/json" -d ''{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'' || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - tee-network
    platform: linux/amd64

  bitcoin-core:
    container_name: tee-bitcoin-core
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bookworm-slim
        RUN apt-get update \
          && apt-get install -y --no-install-recommends \
             ca-certificates \
             curl \
             tar \
             bash \
             lz4 \
             wget \
             aria2 \
          && rm -rf /var/lib/apt/lists/*

        RUN useradd -m -u 1000 -s /bin/bash bitcoin \
          && mkdir -p /home/bitcoin/.bitcoin \
          && chown -R bitcoin:bitcoin /home/bitcoin/.bitcoin
        WORKDIR /opt/bitcoin
        RUN curl -fsSL "https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz" -o bitcoin.tar.gz \
          && tar -xzf bitcoin.tar.gz --strip-components=1 \
          && install -m 0755 -o root -g root -t /usr/local/bin bin/* \
          && rm -rf /opt/bitcoin

        EXPOSE 8332 8333
        VOLUME ["/home/bitcoin/.bitcoin"]
        USER bitcoin
        WORKDIR /home/bitcoin
        ENTRYPOINT ["/usr/local/bin/bitcoin-entrypoint.sh"]
    environment:
      BITCOIN_DATA_DIR: /home/bitcoin/.bitcoin
    command:
      - "-server=1"
      - "-txindex=1"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-datadir=/home/bitcoin/.bitcoin"
      - "-fallbackfee=0.0002"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    configs:
      - source: bitcoin-entrypoint
        target: /usr/local/bin/bitcoin-entrypoint.sh
        mode: 0755
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bitcoin-cli -rpcuser=user -rpcpassword=pass getblockchaininfo > /dev/null || exit 1",
        ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - tee-network
    platform: linux/amd64

  otc-server:
    image: riftresearch/otc-server:main-354a300
    container_name: tee-otc-server
    depends_on:
      postgres:
        condition: service_healthy
      helios:
        condition: service_started
      bitcoin-core:
        condition: service_started
    environment:
      GRANT_SUDO: yes
      DATABASE_URL: postgres://otc_user:otc_password@postgres:5432/otc_db
      RUST_LOG: info
      EVM_RPC_URL: http://helios:8545
      UNTRUSTED_EVM_TOKEN_INDEXER_URL: ${UNTRUSTED_EVM_TOKEN_INDEXER_URL}
      BITCOIN_RPC_URL: http://bitcoin-core:8332
      BITCOIN_RPC_AUTH: user:pass
      ELECTRUM_HTTP_SERVER_URL: ${UNTRUSTED_ELECTRUM_HTTP_SERVER_URL}
      CORS_DOMAIN: "*"
      CHAINALYSIS_HOST: ${CHAINALYSIS_HOST}
      CHAINALYSIS_TOKEN: ${CHAINALYSIS_TOKEN}
      CONFIG_DIR: /app/config
      DSTACK_SOCK_PATH: /var/run/dstack.sock
    ports:
      - "4422:4422"
    networks:
      - tee-network
    volumes:
      - ${DSTACK_SOCK_PATH:-/var/run/dstack.sock}:/var/run/dstack.sock
      - otc_server_config_data:/app/config
    platform: linux/amd64
    user: root

networks:
  tee-network:
    driver: bridge

volumes:
  postgres_data:
  bitcoin_data:
  otc_server_config_data:
