version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: otc-postgres
    environment:
      POSTGRES_USER: otc_user
      POSTGRES_PASSWORD: otc_password
      POSTGRES_DB: otc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otc_user -d otc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - otc-network

  otc-server:
    build:
      context: .
      dockerfile_inline: |
        FROM rust:1.75 as builder
        WORKDIR /app
        COPY . .
        RUN cargo build --release --bin otc-server

        FROM debian:bookworm-slim
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/otc-server /app/
        EXPOSE 3000
        CMD ["./otc-server", "--host", "0.0.0.0"]
    container_name: otc-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://otc_user:otc_password@postgres:5432/otc_db
      RUST_LOG: info
    ports:
      - "3000:3000"
    networks:
      - otc-network

networks:
  otc-network:
    driver: bridge

volumes:
  postgres_data: