[package]
name = "bitcoin-wallet-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rand-bitcoin-wallet"
path = "src/main.rs"


[dependencies]
otc-models = { workspace = true }
argon2 = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
blockchain-utils = { workspace = true }
bitcoin  = {workspace=true}
