services:
  db:
    image: postgres:15-alpine
    container_name: test_db
    command: postgres -c max_connections=200
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 100ms
      timeout: 5s
      retries: 100
    networks:
      - test-network

networks:
  test-network: