services:
  iozone-bench:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bookworm-slim
        RUN apt-get update && apt-get install -y \
            build-essential \
            wget \
            && rm -rf /var/lib/apt/lists/*
        
        # Download and compile iozone from source
        WORKDIR /tmp
        RUN wget https://www.iozone.org/src/current/iozone3_508.tar && \
            tar -xf iozone3_508.tar && \
            cd iozone3_508/src/current && \
            make linux && \
            cp iozone /usr/local/bin/ && \
            rm -rf /tmp/iozone3_508*
        
        WORKDIR /work
        ENTRYPOINT ["/bin/bash", "-lc"]
        CMD ["echo 'Running iozone in /work ...' && iozone -e -t1 -i0 -i2 -r1k -s1g ."]
    container_name: iozone-bench
    volumes:
      - iozone_data:/work
    restart: "no"

volumes:
  iozone_data: