services:
  token-indexer-postgres:
    image: postgres:16-alpine
    container_name: token-indexer-postgres
    environment:
      POSTGRES_USER: token_indexer_user
      POSTGRES_PASSWORD: token_indexer_password
      POSTGRES_DB: token_indexer_db
    volumes: []
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U token_indexer_user -d token_indexer_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rift-network

  devnet: 
    container_name: devnet
    depends_on:
      token-indexer-postgres:
        condition: service_healthy
    platform: linux/amd64
    build:
      context: ..
      platforms:
        - linux/amd64
      dockerfile_inline: |
        FROM rust:1.90.0-trixie AS chef
        RUN cargo install cargo-chef
        WORKDIR /app

        FROM chef AS planner
        COPY . .
        RUN cargo chef prepare --recipe-path recipe.json

        FROM chef AS builder
        COPY --from=planner /app/recipe.json recipe.json
        COPY --from=planner /app/sqlx-sqlite-shim ./sqlx-sqlite-shim
        RUN cargo chef cook --release --recipe-path recipe.json
        COPY . .
        RUN cargo build --release --bin devnet --exclude integration-tests --workspace

        FROM debian:trixie
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            curl \
            && rm -rf /var/lib/apt/lists/*
          
        RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
            apt-get install -y nodejs && \
            npm install -g pnpm@9.14.4

        RUN curl -fsSL https://github.com/foundry-rs/foundry/releases/download/v1.3.6/foundry_v1.3.6_linux_amd64.tar.gz | tar -xzf - -C /usr/local/bin
          
        WORKDIR /app
        COPY --from=builder /app/ /app/
        RUN cd evm-token-indexer && pnpm install && cd ..
        CMD ["./target/release/devnet", "server"]
    environment:
      TOKEN_INDEXER_DATABASE_URL: postgres://token_indexer_user:token_indexer_password@token-indexer-postgres:5432/token_indexer_db
    networks:
      - rift-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://devnet:50104/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "50100:50100"
      - "50101:50101"
      - "50102:50102"
      - "50103:50103"
      - "50104:50104"
      - "50105:50105"
      - "8080:8080"

  otc-server:
    image: !reset null
    build:
      context: ..
      dockerfile_inline: |
        FROM rust:1.90.0-trixie AS chef
        RUN cargo install cargo-chef
        WORKDIR /app

        FROM chef AS planner
        COPY . .
        RUN cargo chef prepare --recipe-path recipe.json

        FROM chef AS builder
        COPY --from=planner /app/recipe.json recipe.json
        COPY --from=planner /app/sqlx-sqlite-shim ./sqlx-sqlite-shim
        RUN cargo chef cook --release --recipe-path recipe.json
        COPY . .
        RUN cargo build --release --bin otc-server --features integration-test --exclude integration-tests --workspace

        FROM debian:trixie
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            curl \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/otc-server /app/
        EXPOSE 4422
        CMD ["./otc-server", "--host", "0.0.0.0", "--port", "4422"]
    depends_on: !override
      pg-secret-generator:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      devnet:
        condition: service_healthy
    entrypoint: ["/usr/local/bin/otc-server-entrypoint.sh"]
    configs:
      - source: otc-server-entrypoint
        target: /usr/local/bin/otc-server-entrypoint.sh
        mode: 0755
    environment:
      GRANT_SUDO: yes
      # DATABASE_URL is constructed dynamically in the entrypoint from sidecar-generated secrets
      RUST_LOG: info 
      # Ethereum configuration (devnet port 50101)
      EVM_RPC_URL: http://devnet:50101
      UNTRUSTED_ETHEREUM_TOKEN_INDEXER_URL: http://devnet:50104
      ETHEREUM_ALLOWED_TOKEN: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
      # Base configuration (devnet port 50102, token indexer port 50105)
      BASE_RPC_URL: http://devnet:50102
      UNTRUSTED_BASE_TOKEN_INDEXER_URL: http://devnet:50105
      BASE_ALLOWED_TOKEN: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
      # Bitcoin configuration (devnet port 50100)
      BITCOIN_RPC_URL: http://devnet:50100
      BITCOIN_RPC_AUTH: bitcoind:bitcoind
      ELECTRUM_HTTP_SERVER_URL: http://devnet:50103
      CORS_DOMAIN: "*"
      CHAINALYSIS_HOST: ~
      CHAINALYSIS_TOKEN: ~
      CONFIG_DIR: /app/config
      DSTACK_SOCK_PATH: /var/run/dstack.sock
      BITCOIN_NETWORK: regtest
      METRICS_LISTEN_ADDR: 0.0.0.0:9000
    volumes: !override
      # Keep all essential volumes from base
      - ${DSTACK_SOCK_PATH:-/var/run/dstack.sock}:/var/run/dstack.sock
      - otc_server_config_data:/app/config
      - pg_secrets:/run/postgres-secrets:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:4422/status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
  
  rfq-server:
    build:
      context: ..
      dockerfile_inline: |
        FROM rust:1.90.0-trixie AS chef
        RUN cargo install cargo-chef
        WORKDIR /app

        FROM chef AS planner
        COPY . .
        RUN cargo chef prepare --recipe-path recipe.json

        FROM chef AS builder
        COPY --from=planner /app/recipe.json recipe.json
        COPY --from=planner /app/sqlx-sqlite-shim ./sqlx-sqlite-shim
        RUN cargo chef cook --release --recipe-path recipe.json
        COPY . .
        RUN cargo build --release --bin rfq-server --features integration-test --exclude integration-tests --workspace

        FROM debian:trixie
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/rfq-server /app/
        EXPOSE 3001
        CMD ["./rfq-server", "--host", "0.0.0.0", "--port", "3001"]
  
    depends_on:
      devnet:
        condition: service_healthy
    environment:
      RUST_LOG: info
      CORS_DOMAIN: "*"
      CHAINALYSIS_HOST: ~
      CHAINALYSIS_TOKEN: ~
    networks:
      - rift-network
    ports:
      - "3001:3001"
    volumes: []


  eth-helios: !reset null

  base-helios: !reset null

  bitcoin-core: !reset null 

  stunnel: !reset null

  postgres:
    environment:
      # Provide replica password for testing (required by base config)
      POSTGRES_REPLICA_PASSWORD: test_replica_password_override
    # Keep all configs, command, and depends_on from base (pg-secret-generator, custom postgres.conf, etc.)
    volumes: !override
      # Keep pg_secrets for secret management, but use ephemeral data storage
      - pg_secrets:/run/postgres-secrets:ro
    networks:
      - rift-network 

  prometheus:
    networks:
    volumes: []

  # ===== ETHEREUM MARKET MAKER STACK =====
  
  mm-postgres-eth:
    image: postgres:16-alpine
    container_name: mm-postgres-eth
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mm_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: []
    networks:
      - mm-network-eth

  market-maker-eth:
    container_name: market-maker-eth
    build:
      context: ..
      dockerfile_inline: |
        FROM rust:1.90.0-trixie AS chef
        RUN cargo install cargo-chef 
        WORKDIR /app

        FROM chef AS planner
        COPY . .
        RUN cargo chef prepare  --recipe-path recipe.json

        FROM chef AS builder
        COPY --from=planner /app/recipe.json recipe.json
        COPY --from=planner /app/sqlx-sqlite-shim ./sqlx-sqlite-shim
        RUN cargo chef cook --release --recipe-path recipe.json
        COPY . .
        RUN cargo build --release --bin market-maker --exclude integration-tests --workspace

        FROM debian:trixie AS runtime
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/market-maker /app/
        CMD ["./market-maker"]
    ports:
      - "9000:9000"
      - "6669:6669"
      - "8081:8081"
    depends_on:
      mm-postgres-eth:
        condition: service_healthy
      devnet:
        condition: service_healthy
      otc-server:
        condition: service_started
      rfq-server:
        condition: service_started
    environment:
      ENABLE_TOKIO_CONSOLE_SUBSCRIBER: false
      RUST_LOG: info
      METRICS_LISTEN_ADDR: 0.0.0.0:9000
      MM_TAG: test-mm-eth
      MM_ID: 96c0bedb-bfda-4680-a8df-1317d1e09c8d
      MM_API_SECRET: Bt7nDfOLlstMLLMvj3dlY3kFozxHk6An
      OTC_WS_URL: ws://otc-server:4422/ws/mm
      RFQ_WS_URL: ws://rfq-server:3001/ws/mm
      BITCOIN_WALLET_DB_PATH: /app/bitcoin-wallet-db/wallet.sqlite
      # bitcoin address: bcrt1qn65u46clcspgdg7ylgdvd5848cg0jzgy0a8lee
      BITCOIN_WALLET_DESCRIPTOR: wpkh(cQzMQbLioizdTAVPHtYWN5bpNoCuZvgDCPvfK2Aker5Q5abnnybJ)
      BITCOIN_WALLET_NETWORK: regtest
      BITCOIN_WALLET_ESPLORA_URL: http://devnet:50103
      # EVM configuration (ethereum)
      # ethereum address: 0x42c0ca15451F626B83f6BA80fDB13A4F59167213
      EVM_CHAIN: ethereum
      EVM_WALLET_PRIVATE_KEY: 1b3a3180231b9b22aee5e31606a33da3685e83d948d7f569f6623143371fceb5
      EVM_CONFIRMATIONS: 1
      EVM_RPC_WS_URL: ws://devnet:50101
      TRADE_SPREAD_BPS: 0
      FEE_SAFETY_MULTIPLIER: 1.5
      BALANCE_UTILIZATION_THRESHOLD_BPS: 9500
      MM_DATABASE_URL: postgres://user:pass@mm-postgres-eth:5432/mm_db
      INVENTORY_TARGET_RATIO_BPS: 5000
      REBALANCE_TOLERANCE_BPS: 2500
      COINBASE_EXCHANGE_API_KEY: ""
      COINBASE_EXCHANGE_API_PASSPHRASE: ""
      COINBASE_EXCHANGE_API_SECRET: ""
      COINBASE_EXCHANGE_API_BASE_URL: http://devnet:8080
      AUTO_MANAGE_INVENTORY: true
      BITCOIN_BATCH_INTERVAL_SECS: 2
      BITCOIN_BATCH_SIZE: 100
      ETHEREUM_BATCH_INTERVAL_SECS: 2
      ETHEREUM_BATCH_SIZE: 392
      LOKI_URL: http://mm-loki-eth:3100
    volumes:
      - market_maker_eth_bitcoin_wallet_db_data:/app/bitcoin-wallet-db
    networks:
      - rift-network
      - mm-network-eth

  mm-loki-eth:
    image: grafana/loki:2.9.10
    container_name: mm-loki-eth
    ports:
      - "3100:3100"
    volumes: []
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    networks:
      - mm-network-eth

  mm-prometheus-eth:
    image: prom/prometheus:v2.54.1
    container_name: mm-prometheus-eth
    volumes: []
    configs:
      - source: mm-prometheus-config-eth
        target: /etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - mm-network-eth

  mm-grafana-eth:
    image: grafana/grafana:12.2.1
    container_name: mm-grafana-eth
    ports:
      - "3010:3000"
    depends_on:
      mm-prometheus-eth:
        condition: service_started
      mm-loki-eth:
        condition: service_started
    configs:
      - source: grafana-datasource-mm-devnet-eth
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana-dashboard-provider-mm
        target: /etc/grafana/provisioning/dashboards/provider.yml
      - source: grafana-node-dashboard-mm
        target: /etc/grafana/provisioning/dashboards/mm-system-metrics.json
    networks:
      - mm-network-eth
  
  # ===== BASE MARKET MAKER STACK =====
  
  mm-postgres-base:
    image: postgres:16-alpine
    container_name: mm-postgres-base
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mm_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: []
    networks:
      - mm-network-base

  market-maker-base:
    container_name: market-maker-base
    build:
      context: ..
      dockerfile_inline: |
        FROM rust:1.90.0-trixie AS chef
        RUN cargo install cargo-chef 
        WORKDIR /app

        FROM chef AS planner
        COPY . .
        RUN cargo chef prepare  --recipe-path recipe.json

        FROM chef AS builder
        COPY --from=planner /app/recipe.json recipe.json
        COPY --from=planner /app/sqlx-sqlite-shim ./sqlx-sqlite-shim
        RUN cargo chef cook --release --recipe-path recipe.json
        COPY . .
        RUN cargo build --release --bin market-maker --exclude integration-tests --workspace

        FROM debian:trixie AS runtime
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/market-maker /app/
        CMD ["./market-maker"]
    ports:
      - "9001:9000"
      - "6670:6669"
      - "8082:8081"
    depends_on:
      mm-postgres-base:
        condition: service_healthy
      devnet:
        condition: service_healthy
      otc-server:
        condition: service_started
      rfq-server:
        condition: service_started
    environment:
      ENABLE_TOKIO_CONSOLE_SUBSCRIBER: false
      RUST_LOG: info
      METRICS_LISTEN_ADDR: 0.0.0.0:9000
      MM_TAG: test-mm-base
      MM_ID: f901369b-84d7-4c03-8799-f504c22125f9
      MM_API_SECRET: 5iAlXNoDVsGvjwiEjqhbLBVOpAN0wFZ8
      OTC_WS_URL: ws://otc-server:4422/ws/mm
      RFQ_WS_URL: ws://rfq-server:3001/ws/mm
      BITCOIN_WALLET_DB_PATH: /app/bitcoin-wallet-db/wallet.sqlite
      # bitcoin address: bcrt1qhgel8jdfcayas5phnxncxejg6w3tgq09v64hqp
      BITCOIN_WALLET_DESCRIPTOR: wpkh(cRGrPaoyLxFxgp41JhLAbHh6x2GJg7nDrSBYUDV8ZAqfe9TS89kp)
      BITCOIN_WALLET_NETWORK: regtest
      BITCOIN_WALLET_ESPLORA_URL: http://devnet:50103
      # EVM configuration (base)
      # base address: 0x956A134e689cC33A5488D75420044CEa25936F84
      EVM_CHAIN: base
      EVM_WALLET_PRIVATE_KEY: 68d2bfbba4cd100067f5878af014c02c21a42f75d88ea90386f72a4a5872836e
      EVM_CONFIRMATIONS: 1
      EVM_RPC_WS_URL: ws://devnet:50102
      TRADE_SPREAD_BPS: 0
      FEE_SAFETY_MULTIPLIER: 1.5
      BALANCE_UTILIZATION_THRESHOLD_BPS: 9500
      MM_DATABASE_URL: postgres://user:pass@mm-postgres-base:5432/mm_db
      INVENTORY_TARGET_RATIO_BPS: 5000
      REBALANCE_TOLERANCE_BPS: 2500
      COINBASE_EXCHANGE_API_KEY: ""
      COINBASE_EXCHANGE_API_PASSPHRASE: ""
      COINBASE_EXCHANGE_API_SECRET: ""
      COINBASE_EXCHANGE_API_BASE_URL: http://devnet:8080
      AUTO_MANAGE_INVENTORY: true
      BITCOIN_BATCH_INTERVAL_SECS: 2
      BITCOIN_BATCH_SIZE: 100
      ETHEREUM_BATCH_INTERVAL_SECS: 2
      ETHEREUM_BATCH_SIZE: 392
      LOKI_URL: http://mm-loki-base:3100
    volumes:
      - market_maker_base_bitcoin_wallet_db_data:/app/bitcoin-wallet-db
    networks:
      - rift-network
      - mm-network-base

  mm-loki-base:
    image: grafana/loki:2.9.10
    container_name: mm-loki-base
    ports:
      - "3101:3100"
    volumes: []
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    networks:
      - mm-network-base

  mm-prometheus-base:
    image: prom/prometheus:v2.54.1
    container_name: mm-prometheus-base
    volumes: []
    configs:
      - source: mm-prometheus-config-base
        target: /etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - mm-network-base

  mm-grafana-base:
    image: grafana/grafana:12.2.1
    container_name: mm-grafana-base
    ports:
      - "3011:3000"
    depends_on:
      mm-prometheus-base:
        condition: service_started
      mm-loki-base:
        condition: service_started
    configs:
      - source: grafana-datasource-mm-devnet-base
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana-dashboard-provider-mm
        target: /etc/grafana/provisioning/dashboards/provider.yml
      - source: grafana-node-dashboard-mm
        target: /etc/grafana/provisioning/dashboards/mm-system-metrics.json
    networks:
      - mm-network-base
  
  replica-setup:
    depends_on:
      postgres-replica:
        condition: service_healthy
      postgres:
        condition: service_healthy
      otc-server:
        condition: service_healthy
    networks:
      - rift-network
    environment:
      # Primary database connection
      PRIMARY_DB_HOST: postgres
      PRIMARY_DB_PORT: ${PRIMARY_DB_PORT:-5432}
      PRIMARY_DB_NAME: ${PRIMARY_DB_NAME:-otc_db}
      PRIMARY_DB_USER: ${PRIMARY_DB_USER:-replicator}
      PRIMARY_DB_PASSWORD: ${PRIMARY_DB_PASSWORD:?PRIMARY_DB_PASSWORD must be set}
      
      # Replica database connection
      REPLICA_DB_HOST: postgres-replica
      REPLICA_DB_PORT: 5432
      REPLICA_DB_NAME: ${REPLICA_DB_NAME:-otc_db}
      REPLICA_DB_USER: ${REPLICA_DB_USER:-postgres}
      REPLICA_DB_PASSWORD: ${REPLICA_DB_PASSWORD:?REPLICA_DB_PASSWORD must be set}
  
  postgres-replica:
    volumes: []
    networks:
      - rift-network 

networks:
  mm-network-eth:
    driver: bridge
  mm-network-base:
    driver: bridge

volumes:
  market_maker_eth_bitcoin_wallet_db_data:
  market_maker_base_bitcoin_wallet_db_data:

configs:
  # Shared market-maker configs (referenced from external files)
  prometheus-config-mm:
    file: configs/mm-prometheus-config.yml

  loki-config-mm:
    file: configs/mm-loki-config.yml

  grafana-datasource-mm:
    file: configs/mm-grafana-datasource.yml

  grafana-dashboard-provider-mm:
    file: configs/mm-grafana-dashboard-provider.yml

  grafana-node-dashboard-mm:
    file: configs/mm-grafana-dashboard.json

  # Environment-specific datasource configs (point to correct Prometheus/Loki instances)
  grafana-datasource-mm-devnet-eth:
    file: configs/mm-grafana-datasource-devnet-eth.yml

  grafana-datasource-mm-devnet-base:
    file: configs/mm-grafana-datasource-devnet-base.yml

  # Per-environment specific configs
  mm-prometheus-config-eth:
    content: |
      global:
        scrape_interval: 5s
        evaluation_interval: 5s

      scrape_configs:
        - job_name: 'market-maker'
          static_configs:
            - targets: ['market-maker-eth:9000']
  
  mm-prometheus-config-base:
    content: |
      global:
        scrape_interval: 5s
        evaluation_interval: 5s

      scrape_configs:
        - job_name: 'market-maker'
          static_configs:
            - targets: ['market-maker-base:9000']
