configs:
  prometheus-config-mm:
    file: configs/mm-prometheus-config.yml

  loki-config-mm:
    file: configs/mm-loki-config.yml

  grafana-datasource-mm:
    file: configs/mm-grafana-datasource.yml

  grafana-dashboard-provider-mm:
    file: configs/mm-grafana-dashboard-provider.yml

  grafana-node-dashboard-mm:
    file: configs/mm-grafana-dashboard.json


services:
  mm-postgres:
    image: postgres:16-alpine
    container_name: mm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mm_db
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "work_mem=2MB"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
    volumes:
      - mm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: 1g
    networks:
      - mm-network

  market-maker:
    container_name: market-maker
    restart: unless-stopped
    build:
      context: ..
      dockerfile_inline: |
        FROM rust:1.90.0-trixie AS chef
        RUN cargo install cargo-chef 
        WORKDIR /app

        FROM chef AS planner
        COPY . .
        RUN cargo chef prepare  --recipe-path recipe.json

        FROM chef AS builder
        COPY --from=planner /app/recipe.json recipe.json
        # Copy the sqlx-sqlite-shim directory which is needed for the path dependency
        COPY --from=planner /app/sqlx-sqlite-shim ./sqlx-sqlite-shim
        # Build dependencies - this is the caching Docker layer!
        RUN cargo chef cook --release --recipe-path recipe.json
        # Build application
        COPY . .
        RUN cargo build --release --bin market-maker --exclude integration-tests --workspace

        FROM debian:trixie AS runtime
        RUN apt-get update && apt-get install -y \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY --from=builder /app/target/release/market-maker /app/
        CMD ["./market-maker"]
    depends_on:
      mm-postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
      - "6669:6669"
    environment:
      ENABLE_TOKIO_CONSOLE_SUBSCRIBER: ${ENABLE_TOKIO_CONSOLE_SUBSCRIBER}
      RUST_LOG: ${RUST_LOG} 
      METRICS_LISTEN_ADDR: 0.0.0.0:9000
      ADMIN_API_LISTEN_ADDR: 0.0.0.0:8081
      MM_TAG: ${MM_TAG}
      MM_ID: ${MM_ID}
      MM_API_SECRET: ${MM_API_SECRET}
      OTC_WS_URL: ${OTC_WS_URL}
      RFQ_WS_URL: ${RFQ_WS_URL}
      BITCOIN_WALLET_DB_PATH: /app/bitcoin-wallet-db/wallet.sqlite
      BITCOIN_WALLET_DESCRIPTOR: ${BITCOIN_WALLET_DESCRIPTOR}
      BITCOIN_WALLET_NETWORK: bitcoin
      BITCOIN_WALLET_ESPLORA_URL: ${BITCOIN_WALLET_ESPLORA_URL}
      # EVM configuration (ethereum or base)
      EVM_CHAIN: ${EVM_CHAIN:-ethereum}
      EVM_WALLET_PRIVATE_KEY: ${EVM_WALLET_PRIVATE_KEY}
      EVM_CONFIRMATIONS: ${EVM_CONFIRMATIONS:-2}
      EVM_RPC_WS_URL: ${EVM_RPC_WS_URL}
      TRADE_SPREAD_BPS: ${TRADE_SPREAD_BPS}
      FEE_SAFETY_MULTIPLIER: ${FEE_SAFETY_MULTIPLIER}
      BALANCE_UTILIZATION_THRESHOLD_BPS: ${BALANCE_UTILIZATION_THRESHOLD_BPS}
      MM_DATABASE_URL: postgres://user:pass@mm-postgres:5432/mm_db
      COINBASE_EXCHANGE_API_KEY: ${COINBASE_EXCHANGE_API_KEY}
      COINBASE_EXCHANGE_API_PASSPHRASE: ${COINBASE_EXCHANGE_API_PASSPHRASE}
      COINBASE_EXCHANGE_API_SECRET: ${COINBASE_EXCHANGE_API_SECRET}
      COINBASE_EXCHANGE_API_BASE_URL: https://api.exchange.coinbase.com
      INVENTORY_TARGET_RATIO_BPS: ${INVENTORY_TARGET_RATIO_BPS}
      REBALANCE_TOLERANCE_BPS: ${REBALANCE_TOLERANCE_BPS}
      AUTO_MANAGE_INVENTORY: ${AUTO_MANAGE_INVENTORY}
      FEE_SETTLEMENT_RAIL: ${FEE_SETTLEMENT_RAIL:-evm}
      FEE_SETTLEMENT_INTERVAL_SECS: ${FEE_SETTLEMENT_INTERVAL_SECS:-300}
      LOKI_URL: http://mm-loki:3100

    networks:
      - mm-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - market_maker_bitcoin_wallet_db_data:/app/bitcoin-wallet-db

  mm-node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: mm-node-exporter
    restart: unless-stopped
    pid: host
    command:
      - "--path.rootfs=/rootfs"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - mm-network

  mm-prometheus:
    image: prom/prometheus:v2.54.1
    container_name: mm-prometheus
    restart: unless-stopped
    depends_on:
      mm-node-exporter:
        condition: service_started
    volumes:
      - mm_prometheus_data:/prometheus
    configs:
      - source: prometheus-config-mm
        target: /etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - mm-network

  mm-loki:
    image: grafana/loki:2.9.10
    container_name: mm-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - mm_loki_data:/loki
    configs:
      - source: loki-config-mm
        target: /etc/loki/local-config.yaml
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    networks:
      - mm-network

  mm-grafana:
    image: grafana/grafana:12.2.1
    container_name: mm-grafana
    restart: unless-stopped
    ports:
      - "3010:3000"
    depends_on:
      mm-prometheus:
        condition: service_started
      mm-loki:
        condition: service_started
    configs:
      - source: grafana-datasource-mm
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana-dashboard-provider-mm
        target: /etc/grafana/provisioning/dashboards/provider.yml
      - source: grafana-node-dashboard-mm
        target: /etc/grafana/provisioning/dashboards/mm-system-metrics.json
    networks:
      - mm-network

networks:
  mm-network:
    driver: bridge

volumes:
  mm_postgres_data:
  market_maker_bitcoin_wallet_db_data:
  mm_prometheus_data:
  mm_loki_data:
