[package]
name = "mm-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "mm-server"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures = "0.3"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
otc-mm-protocol = { workspace = true }
otc-models = { workspace = true }
alloy = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
url = "2.5" 
snafu = { workspace = true }
rand = "0.8"
lazy_static = "1.5.0"
anyhow = "1.0"
async-trait = "0.1.86"