[package]
name = "rfq-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rfq-server"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }