[package]
name = "tx-flood"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alloy = { workspace = true }
anyhow = "1.0"
bitcoin = { workspace = true }
blockchain-utils = { workspace = true }
clap = { workspace = true, features = ["derive"] }
crossterm = "0.27"
futures-util = { workspace = true }
humantime = "2.1"
market-maker = { workspace = true }
otc-models = { workspace = true }
otc-protocols = { workspace = true }
otc-server = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
rfq-server = { workspace = true }
ratatui = "0.28"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
uuid = { workspace = true }
chrono = { workspace = true }
tempfile = {workspace=true}
