[package]
name = "tx-flood"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
humantime = { workspace = true }
anyhow = { workspace = true }
crossterm = { workspace = true }
dotenvy = { workspace = true }
ratatui = { workspace = true }
alloy = { workspace = true }
bitcoin = { workspace = true }
blockchain-utils = { workspace = true }
clap = { workspace = true, features = ["derive"] }
futures-util = { workspace = true }
market-maker = { workspace = true }
otc-models = { workspace = true }
otc-protocols = { workspace = true }
otc-server = { workspace = true }
rustls = {workspace=true}
reqwest = { workspace = true, features = ["json"] }
rfq-server = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
uuid = { workspace = true }
chrono = { workspace = true }
tempfile = {workspace=true}
eip3009-erc20-contract = {workspace=true}
snafu = {workspace=true}
eip7702-delegator-contract = { workspace = true }
rand = { workspace = true }
