[package]
name = "market-maker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "market-maker"
path = "src/main.rs"

[dependencies]
common = {workspace = true}
otc-models = { workspace = true }
otc-mm-protocol = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
snafu = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }

[dev-dependencies]