[package]
name = "market-maker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "market-maker"
path = "src/main.rs"

[dependencies]
blockchain-utils = {workspace = true}
otc-models = { workspace = true }
otc-protocols = { workspace = true }
otc-chains = {workspace=true}

alloy = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
snafu = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
bdk_wallet = { workspace = true }
bdk_esplora = { workspace = true }
sqlx = { workspace = true }
esplora-client = {workspace=true}

eip7702-delegator-contract = {workspace=true}
eip3009-erc20-contract = {workspace=true}
reqwest = {workspace=true}
jsonwebtoken = {workspace=true}


p256 = {workspace=true}
metrics = {workspace=true}
hmac = {workspace=true}
sha2 = {workspace=true}
base64 = {workspace=true}


[dev-dependencies]
