configs:
  prometheus-config-mm:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
                - prometheus:9090
        - job_name: node-exporter
          static_configs:
            - targets:
                - node-exporter:9100
        - job_name: market-maker
          static_configs:
            - targets:
                - rift-market-maker:9000

  grafana-datasource-mm:
    content: |
      apiVersion: 1
      deleteDatasources:
        - name: Prometheus
      datasources:
        - name: Prometheus
          uid: PBFA97CFB590B2093
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true

  grafana-dashboard-provider-mm:
    content: |
      apiVersion: 1
      providers:
        - name: Default
          orgId: 1
          folder: ""
          type: file
          options:
            path: /etc/grafana/provisioning/dashboards

  grafana-node-dashboard-mm:
    content: |
      {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "name": "grafana"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 1,
        "links": [],
        "panels": [
          {
            "datasource": {
              "type": "prometheus",
              "name": "Prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "unit": "percent"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "id": 1,
            "options": {
              "legend": {
                "displayMode": "hidden"
              },
              "tooltip": {
                "mode": "multi",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "name": "Prometheus"
                },
                "editorMode": "code",
                "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100",
                "legendFormat": "CPU Usage",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Host CPU Usage",
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "prometheus",
              "name": "Prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "unit": "gbytes"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 8
            },
            "id": 2,
            "options": {
              "legend": {
                "displayMode": "hidden"
              },
              "tooltip": {
                "mode": "multi",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "name": "Prometheus"
                },
                "editorMode": "code",
                "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / 1024 / 1024 / 1024",
                "legendFormat": "Memory Used",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Host Memory Usage",
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "prometheus",
              "name": "Prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "unit": "gbytes"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 16
            },
            "id": 3,
            "options": {
              "legend": {
                "displayMode": "list",
                "placement": "right",
                "showLegend": true
              },
              "tooltip": {
                "mode": "multi",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "name": "Prometheus"
                },
                "editorMode": "code",
                "expr": "(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\", mountpoint!~\"/(sys|proc|dev|run)(/.*)?\"} - node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\", mountpoint!~\"/(sys|proc|dev|run)(/.*)?\"}) / 1024 / 1024 / 1024",
                "legendFormat": "{{mountpoint}}",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Disk Usage by Mount",
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "prometheus",
              "name": "Prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "unit": "currencyBTC"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 24
            },
            "id": 4,
            "options": {
              "legend": {
                "displayMode": "list",
                "placement": "right",
                "showLegend": true
              },
              "tooltip": {
                "mode": "multi",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "name": "Prometheus"
                },
                "editorMode": "code",
                "expr": "mm_balance_sats / 1e8",
                "legendFormat": "{{asset}}",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Inventory Balance (BTC)",
            "type": "timeseries"
          }
        ],
        "refresh": "30s",
        "schemaVersion": 38,
        "style": "dark",
        "tags": [
          "monitoring"
        ],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "",
        "title": "MM System Metrics",
        "uid": "mm-system-metrics",
        "version": 2,
        "weekStart": ""
      }
