[package]
name = "otc-chains"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
otc-models = { workspace = true }
async-trait = "0.1"
snafu = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

# Bitcoin dependencies
bitcoin = "0.32"
bitcoincore-rpc = "0.19"

# Ethereum dependencies (using Alloy)
alloy = { workspace = true }

# Common
rust_decimal = { version = "1.35", features = ["serde-with-str"] }
rand = "0.8"