[package]
name = "otc-rfq-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
otc-models = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }